// import { API_BASE_LINK } from "./baseUrl";

// export const APIS = {
//     ADMIN_LOGIN: API_BASE_LINK + `/api/v1/admin/login`,
//     COUNTRY_ADD: API_BASE_LINK + `/api/v1/location/addCountry`,
//     COUNTRY_LIST: API_BASE_LINK + `/api/v1/location/getCountries`,
//     COUNTRY_UPDATE: API_BASE_LINK + `/api/v1/location/updateCountry/`,
//     COUNTRY_DELETE: API_BASE_LINK + `/api/v1/location/deleteCountry/`,
//     STATE_ADD: API_BASE_LINK + `/api/v1/location/addState`,
//     STATE_LIST: API_BASE_LINK + `/api/v1/location/getStates`,
//     STATE_UPDATE: API_BASE_LINK + `/api/v1/location/updateState/`,
//     STATE_DELETE: API_BASE_LINK + `/api/v1/location/deleteState/`,
//     CITY_ADD: API_BASE_LINK + `/api/v1/location/addCity`,
//     CITY_LIST: API_BASE_LINK + `/api/v1/location/getCities`,
//     CITY_UPDATE: API_BASE_LINK + `/api/v1/location/updateCity/`,
//     CITY_DELETE: API_BASE_LINK + `/api/v1/location/deleteCity/`,
//     COURSE_CATEGORY_ADD: API_BASE_LINK + `/api/v1/course/courseCategory/add`,
//     COURSE_CATEGORY_LIST: API_BASE_LINK + `/api/v1/course/courseCategory/all`,
//     COURSE_CATEGORY_UPDATE: API_BASE_LINK + `/api/v1/course/courseCategory/update/`,
//     COURSE_CATEGORY_DELETE: API_BASE_LINK + `/api/v1/course/courseCategory/delete/`,
//     COURSE_SUB_CATEGORY_ADD: API_BASE_LINK + `/api/v1/course/courseSubCategory/add`,
//     COURSE_SUB_CATEGORY_LIST: API_BASE_LINK + `/api/v1/course/courseSubCategory/all`,
//     COURSE_SUB_CATEGORY_UPDATE: API_BASE_LINK + `/api/v1/course/courseSubCategory/update/`,
//     COURSE_SUB_CATEGORY_DELETE: API_BASE_LINK + `/api/v1/course/courseSubCategory/delete/`,
//     COURSE_ADD: API_BASE_LINK + `/api/v1/course/add`,
//     COURSE_LIST: API_BASE_LINK + `/api/v1/course/all`,
//     COURSE_UPDATE: API_BASE_LINK + `/api/v1/course/update/`,
//     COURSE_DELETE: API_BASE_LINK + `/api/v1/course/delete/`,
//     MENTOR_LIST: API_BASE_LINK + `/api/v1/mentor/all`,
//     MENTOR_ADD_WITH_EMAIL_PASSWORD: API_BASE_LINK + `/api/v1/mentor/register/email`,
//     MENTOR_ADD_WITH_MOBILE_PASSWORD: API_BASE_LINK + `/api/v1/mentor/register/mobile`,
//     MENTOR_DELETE_PERMANENTLY: API_BASE_LINK + `/api/v1/mentor/delete/`,
// }



export const APIS = {
    ADMIN_LOGIN: `/api/v1/admin/login`,
    COUNTRY_ADD: `/api/v1/location/addCountry`,
    COUNTRY_LIST: `/api/v1/location/getCountries`,
    COUNTRY_UPDATE: `/api/v1/location/updateCountry/`,
    COUNTRY_DELETE: `/api/v1/location/deleteCountry/`,
    STATE_ADD: `/api/v1/location/addState`,
    STATE_LIST: `/api/v1/location/getStates`,
    STATE_UPDATE: `/api/v1/location/updateState/`,
    STATE_DELETE: `/api/v1/location/deleteState/`,
    CITY_ADD: `/api/v1/location/addCity`,
    CITY_LIST: `/api/v1/location/getCities`,
    CITY_UPDATE: `/api/v1/location/updateCity/`,
    CITY_DELETE: `/api/v1/location/deleteCity/`,
    COURSE_CATEGORY_ADD: `/api/v1/course/courseCategory/add`,
    COURSE_CATEGORY_LIST: `/api/v1/course/courseCategory/all`,
    COURSE_CATEGORY_UPDATE: `/api/v1/course/courseCategory/update/`,
    COURSE_CATEGORY_DELETE: `/api/v1/course/courseCategory/delete/`,
    COURSE_SUB_CATEGORY_ADD: `/api/v1/course/courseSubCategory/add`,
    COURSE_SUB_CATEGORY_LIST: `/api/v1/course/courseSubCategory/all`,
    COURSE_SUB_CATEGORY_UPDATE: `/api/v1/course/courseSubCategory/update/`,
    COURSE_SUB_CATEGORY_DELETE: `/api/v1/course/courseSubCategory/delete/`,
    COURSE_ADD: `/api/v1/course/add`,
    COURSE_LIST: `/api/v1/course/all`,
    COURSE_UPDATE: `/api/v1/course/update/`,
    COURSE_DELETE: `/api/v1/course/delete/`,
    MENTOR_LIST: `/api/v1/mentor/all`,
    MENTOR_ADD_WITH_EMAIL_PASSWORD: `/api/v1/mentor/register/email`,
    MENTOR_ADD_WITH_MOBILE_PASSWORD: `/api/v1/mentor/register/mobile`,
    MENTOR_DELETE_PERMANENTLY: `/api/v1/mentor/delete/`,
}